//
// Created by robnoo on 21/12/21.
//

#ifndef DOODLEJUMP_EVENTTYPE_H
#define DOODLEJUMP_EVENTTYPE_H

enum EventType {UNDEFINED, KEY_PRESSED, REACHED_HEIGHT, PLAYER_USES_BONUS};

#endif //DOODLEJUMP_EVENTTYPE_H
