//
// Created by robnoo on 21/12/21.
//

#ifndef DOODLEJUMP_GAMEEVENTTYPE_H
#define DOODLEJUMP_GAMEEVENTTYPE_H

enum GameEventType {UNDEFINED, KEY_PRESSED, REACHED_HEIGHT, PLAYER_USES_BONUS, PLAYER_BOUNCES_ON_PLATFORM};

#endif //DOODLEJUMP_GAMEEVENTTYPE_H
