//
// Created by robnoo on 21/12/21.
//

#ifndef DOODLEJUMP_GAMEEVENTTYPE_H
#define DOODLEJUMP_GAMEEVENTTYPE_H

enum GameEventType {UNDEFINED, KEY_PRESSED, HEIGHT_CHANGED, PLAYER_USES_BONUS, PLAYER_BOUNCES_ON_PLATFORM, PLAYER_DIED};

#endif //DOODLEJUMP_GAMEEVENTTYPE_H
