//
// Created by robnoo on 6/01/22.
//

#ifndef DOODLEJUMP_KEYBOARD_H
#define DOODLEJUMP_KEYBOARD_H

enum Keyboard {A, D, SPACEBAR, ARROW_LEFT, ARROW_RIGHT, UNDEFINED_KEYBOARD_KEY};

#endif //DOODLEJUMP_KEYBOARD_H
