//
// Created by robnoo on 6/01/22.
//

#ifndef DOODLEJUMP_WINDOWEVENTTYPE_H
#define DOODLEJUMP_WINDOWEVENTTYPE_H

enum WindowEventType {WINDOW_CLOSED, KEY_RELEASED, UNDEFINED_WINDOW_EVENT};

#endif //DOODLEJUMP_WINDOWEVENTTYPE_H
