//
// Created by robnoo on 24/12/21.
//

#ifndef DOODLEJUMP_MISSINGRESOURCEEXCEPTION_H
#define DOODLEJUMP_MISSINGRESOURCEEXCEPTION_H


class MissingResourceException {

};


#endif //DOODLEJUMP_MISSINGRESOURCEEXCEPTION_H
